language: android

jdk:
 - oraclejdk7

before_install:
 - chmod +x gradlew

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew build

notifications:
  email: true

sudo: false